GROQ_API_KEY = "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"
ORS_API_KEY = "eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6ImJkYTMzYzczNzc1ZTQ5YjRhODhmN2FmZWFiN2Q2YWQ0IiwiaCI6Im11cm11cjY0In0="
